AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  predict-lambda

  Sample SAM Template for predict-lambda

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
  Function:
    Timeout: 30

Resources:
  ModelBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  LambdaAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - Fn::Sub: "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyName: ModelBucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action: ["s3:GetObject"]
              Effect: "Allow"
              Resource:
                - Fn::Sub: 'arn:${AWS::Partition}:s3:::${ModelBucket}/*'

  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 3008
      CodeUri: code/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role:
        Fn::GetAtt: LambdaAccessRole.Arn
      Environment:
        Variables:
          s3Bucket: !Ref ModelBucket
          alcohol: clf_alcohol.pkl
          cocever: clf_cocever.pkl
          crkever: clf_crkever.pkl
          herever: clf_herever.pkl
          impsoc: clf_impsoc.pkl
          metha: clf_metha.pkl
          tobacco: clf_tobacco.pkl
          impwork: clf_impwork.pkl
      Events:
        Predict:
          Type: Api
          Properties:
            Path: "/predict"
            Method: get
